// Automatic CZ -> VI gloss for product names (dictionary-based, works offline).
// window.viTranslate(czechName) -> Vietnamese subtitle. Unknown words are kept.
// Dùng chung cho web (Objednavka.dc.html) và cho scripts/update-*.mjs khi sinh products.json.
//
// Thứ tự xử lý: CỤM TỪ (nhiều chữ, phụ thuộc ngữ cảnh) -> TỪ ĐƠN (theo gốc từ + đuôi biến cách).
// Từ nào không có trong từ điển thì giữ nguyên tiếng Séc.
(function () {

// gốc từ + tối đa 4 chữ cái đuôi biến cách (plastový/plastová/plastové/plastových…)
function stem(p) { return '(?<!\\p{L})(?:' + p + ')\\p{L}{0,4}(?!\\p{L})'; }
// khớp đúng chữ, không cho đuôi
function word(p) { return '(?<![\\p{L}\\d])(?:' + p + ')(?![\\p{L}\\d])'; }

// ---------------------------------------------------------------- CỤM TỪ
// Đặt trước từ đơn vì phụ thuộc ngữ cảnh: "dřezová baterie" = vòi nước, còn "baterie" = pin.
var PHRASES = [
 // --- cấp thoát nước ---
 ['(dřezov|umyvadlov|vanov|sprchov|stěnov|stojánkov|kuchyňsk)\\p{L}{0,3}(\\s+\\p{L}+)?\\s+baterie', 'vòi nước'],
 ['baterie\\s+(dřezov|umyvadlov|vanov|sprchov)\\p{L}{0,3}', 'vòi nước'],
 ['rohový ventil', 'van góc'],
 ['kulový (kohout|ventil)', 'van bi'],
 ['zpětn\\p{L}{0,3} (klapka|ventil)', 'van một chiều'],
 ['redukční ventil', 'van giảm áp'],
 ['pod hlavici', 'dưới đầu van'],
 ['přečerpávací hadice', 'ống hút chuyển'],
 ['pračka myčka', 'máy giặt máy rửa bát'],
 ['užitkov\\p{L}{0,3} vod\\p{L}{0,2}|užitkovou vodu', 'nước sinh hoạt'],
 ['pitn\\p{L}{0,3} vod\\p{L}{0,2}|pitnou vodu', 'nước uống'],
 ['odpadní vod\\p{L}{0,2}', 'nước thải'],
 ['na vodovodní kohoutek', 'cho vòi nước'],
 // --- gioăng, khớp nối ---
 ['SADA těsnění', 'Bộ gioăng'],
 ['do hadicových spojek', 'cho khớp nối ống mềm'],
 ['hadicov\\p{L}{0,3} spojk\\p{L}{0,2}', 'khớp nối ống mềm'],
 ['do šroubení', 'cho đầu nối ren'],
 ['převlečn\\p{L}{0,3} matic\\p{L}{0,2}', 'đai ốc chụp'],
 ['O kroužk\\p{L}{0,2}', 'vòng O'],
 ['manžeta do WC', 'măng sông WC'],
 // --- dụng cụ, ngữ cảnh ---
 ['nástrčn\\p{L}{0,3} hlavic\\p{L}{0,2}|nástrčn\\p{L}{0,3} klíč\\p{L}{0,2}', 'đầu tuýp'],
 ['ráčn\\p{L}{0,3} (klíč|hlavic)\\p{L}{0,3}', 'cần siết tự động'],
 ['očkoploch\\p{L}{0,3} klíč|klíč očkoploch\\p{L}{0,3}', 'cờ lê vòng miệng'],
 ['stavitelný klíč|klíč stavitelný', 'mỏ lết'],
 ['momentov\\p{L}{0,3} klíč|klíč momentov\\p{L}{0,3}', 'cờ lê lực'],
 ['imbusov\\p{L}{0,3} klíč|klíč imbus\\p{L}{0,3}', 'lục giác'],
 ['pilový (kotouč|list|plátek|pás)', 'lưỡi cưa'],
 ['řezný kotouč|kotouč řezný', 'đá cắt'],
 ['brusný kotouč|kotouč brusný', 'đá mài'],
 ['brusn\\p{L}{0,3} (papír|plátno)', 'giấy nhám'],
 ['lamelový kotouč', 'nhám xếp'],
 ['vykružovací (korunka|pila)|děrovací pila', 'mũi khoét lỗ'],
 ['hadovitý vrták|vrták hadovitý', 'mũi khoan xoắn dài cho gỗ'],
 ['ploch\\p{L}{0,3} vrták|lopatkový vrták', 'mũi khoan đuôi cá'],
 ['stupňovitý vrták', 'mũi khoan bậc'],
 ['sada vrtáků|vrtáky sada', 'bộ mũi khoan'],
 ['montážní pěna|PU pěna|pěna montážní', 'bọt nở PU'],
 ['stavební chemie', 'hóa chất xây dựng'],
 ['na nejrůznější použití|na nejrůz\\. použití', 'đa dụng'],
 ['pro kutily', 'cho thợ tự làm'],
 ['s věšákem|s věšáčkem', 'có móc treo'],
 ['s (rukojetí|ručkou)', 'có tay cầm'],
 ['s násadou|včetně násady', 'kèm cán'],
 ['bez násady', 'không cán'],
 ['bez EANu', 'không mã EAN'],
 ['s tyčí', 'có cán'],
 ['náhradní (díl|náplň|hlavice)', 'phụ tùng thay thế'],
 ['s vypínačem', 'có công tắc'],
 ['s (víkem|víčkem)', 'có nắp'],
 ['s (uchem|madlem)', 'có quai'],
 ['na (silikon|kartuše)', 'bắn silicon'],
 ['do (mikrovlnky|mikro\\.? ?trouby)', 'dùng lò vi sóng'],
 ['na pečení', 'để nướng'],
 ['na (myčku|nádobí)', 'rửa bát'],
 ['na (mytí auta|auto)', 'rửa xe'],
 ['na okna', 'lau kính'],
 ['na podlahu|na podlahy', 'lau sàn'],
 ['na (dlaždice|dlažbu|obklady)', 'cho gạch ốp lát'],
 ['do (zdiva|betonu)', 'cho tường bê tông'],
 ['do (dřeva|dřeva a plastu)', 'cho gỗ'],
 ['do kovu', 'cho kim loại'],
 ['do (skla|skla a obkladů)', 'cho kính'],
 ['na (kov|ocel)', 'cho kim loại'],
 ['na (dřevo|dřevo a plast)', 'cho gỗ'],
 ['na (kámen|beton)', 'cho đá bê tông'],
 ['na plech', 'cắt tôn'],
 ['na (silné )?větve', 'tỉa cành to'],
 ['na živý plot', 'tỉa hàng rào'],
 ['na (trávník|trávu)', 'cho bãi cỏ'],
 ['proti (hmyzu|komárům|mouchám)', 'chống côn trùng'],
 ['proti (plevelu|plevel)', 'diệt cỏ'],
 ['proti (mravencům|slimákům|molům|hlodavcům)', 'diệt sâu bọ'],
 ['proti (plísni|plísním)', 'chống nấm mốc'],
 ['proti (krtkům|zvěři|ptákům)', 'xua đuổi động vật'],
 ['proti vodnímu kameni', 'chống cặn vôi'],
 ['do (deště|vody)', 'chống nước'],
 ['pro (děti|dětské)', 'cho trẻ em'],
 ['pro (psy|zvířata)', 'cho vật nuôi'],
 ['s (potiskem|nápisem)', 'có in chữ'],
 ['pod (květník|květináč)', 'cho chậu hoa'],
 ['na (květiny|rostliny|popínavé rostliny)', 'cho cây'],
 ['do (pasu|pásu)', 'lưng thường'],
 ['s laclem', 'yếm'],
 ['krátký rukáv|krátkým rukávem', 'tay ngắn'],
 ['dlouhý rukáv|dlouhým rukávem', 'tay dài'],
 ['s kapucí', 'có mũ trùm'],
 ['staré typy', 'loại cũ'],
 ['nové typy', 'loại mới'],
 ['sada utěrek', 'bộ khăn lau'],
 ['dárkov\\p{L}{0,3} sad\\p{L}{0,2}', 'bộ quà tặng'],
 ['bez obalu', 'không hộp'],
 ['v (kufříku|kufru|blistru|krabičce|sáčku)', 'đóng hộp'],
 ['ks/balení|ks/bal\\.?|ks v balení', 'cái/gói'],
 ['zdarma', 'tặng kèm'],
 ['bezpečnostn\\p{L}{0,3} (polobotk|obuv|sandál|bot|kotníkov)\\p{L}{0,3}', 'giày bảo hộ'],
 ['dřevěn\\p{L}{0,3} násad\\p{L}{0,2}|násad\\p{L}{0,2} dřevěn\\p{L}{0,3}', 'cán gỗ'],
 ['ve skle', 'trong ly thủy tinh'],
 ['pokojov\\p{L}{0,3} rostlin\\p{L}{0,2}', 'cây trong nhà'],
 ['balkónov\\p{L}{0,3} rostlin\\p{L}{0,2}', 'cây ban công'],
 ['s klopou a drukem', 'có nắp gập và nút bấm'],
 ['s (potiskem|potisk)', 'có in hình'],
 ['s (oky|očky)', 'có khuyên'],
 ['se síťovinou', 'có lưới'],
 ['(šesti|dvanácti)hran\\p{L}{0,3}', 'lục giác'],
 ['s (gumou|gumovou)', 'có cao su'],
 ['vykružovací korunk\\p{L}{0,2}|korunk\\p{L}{0,2} vykružovac\\p{L}{0,3}', 'mũi khoét lỗ'],
 ['diamantov\\p{L}{0,3} korunk\\p{L}{0,2}', 'mũi khoét kim cương'],
 ['tavn\\p{L}{0,3} pistol\\p{L}{0,2}', 'súng bắn keo nến'],
 ['vytlačovac\\p{L}{0,3} pistol\\p{L}{0,2}|pistol\\p{L}{0,2} na (pěnu|tmel)', 'súng bơm keo'],
 ['stříkac\\p{L}{0,3} pistol\\p{L}{0,2}', 'súng phun sơn'],
 ['s (kapucí|límcem)', 'có mũ'],
 ['plynov\\p{L}{0,3} kartuš\\p{L}{0,2}|kartuš\\p{L}{0,2} plynov\\p{L}{0,3}', 'bình gas mini'],
 ['zemní vrut|vrut zemní', 'vít neo đất'],
 ['stojk\\p{L}{0,2} bedn[íi]c\\p{L}{0,3}|bedn[íi]c\\p{L}{0,3} stojk\\p{L}{0,2}', 'cây chống cốp pha'],
 ['proti (špíně|špíne)', 'chống bẩn'],
 ['na tesařské tužky', 'cho bút chì thợ mộc'],
];

// ---------------------------------------------------------------- TỪ ĐƠN
// [gốc từ (regex), nghĩa tiếng Việt] — khớp gốc + tối đa 4 chữ đuôi biến cách.
var STEMS = [
 // ===== dụng cụ cầm tay =====
 ['kleště|kleštin', 'kìm'], ['šroubovák|šroubovák', 'tua vít'], ['šroubovac', 'vặn vít'],
 ['kladiv', 'búa'], ['palic|perlík', 'búa tạ'], ['sekáč', 'đục'], ['dláto|dlát', 'đục gỗ'],
 ['pilník|pilníc', 'giũa'], ['rašpl', 'giũa thô'], ['pilk', 'cưa nhỏ'], ['pil(a|y|ou|e)', 'cưa'],
 ['svěrák', 'ê tô'], ['svěrk|svork|ztužidl', 'kẹp'], ['páčidl', 'xà beng'],
 ['nůžk|nožic', 'kéo'], ['nůž|nože|nožů', 'dao'], ['čepel', 'lưỡi dao'],
 ['sponkovač', 'máy bắn ghim'], ['nýtovač', 'kìm rivê'], ['nýt', 'đinh rivê'],
 ['průbojník|důlčík', 'đột'], ['hoblík', 'bào tay'], ['nebozez', 'khoan tay'],
 ['klíč', 'cờ lê'], ['hasák', 'mỏ lết ống'], ['ráčn', 'cần siết'],
 ['brašn', 'túi đồ nghề'], ['kufr|kufřík', 'hộp đồ nghề'], ['organizér|organizer', 'khay chia'],
 // ===== phụ kiện máy =====
 ['vrták|vrtác|vrták', 'mũi khoan'], ['vrtac', 'khoan'],
 ['fréz', 'dao phay'], ['sukovník', 'mũi khoét gỗ'], ['závitník', 'mũi taro'],
 ['kotouč', 'đĩa'], ['výsek', 'miếng nhám tròn'], ['unašeč', 'đế gắn nhám'],
 ['brusiv|brusn', 'nhám'], ['brousek|brousk', 'đá mài tay'], ['zrnitost|hrubost', 'độ hạt'],
 ['kartáč', 'bàn chải'], ['bit(y|ů|u)?', 'đầu vít'], ['nástavec|nástavc', 'đầu nối dài'],
 ['adaptér|adaptor', 'đầu chuyển'], ['sklíčidl', 'đầu kẹp mũi khoan'],
 ['hlavic', 'đầu'], ['stopk', 'chuôi'], ['plátek|plátk', 'lưỡi'],
 ['leštic|lešt', 'đánh bóng'], ['tělísk', 'đầu mài nhỏ'],
 // ===== máy móc =====
 ['bruska|brusk', 'máy mài'], ['vrtačk', 'máy khoan'], ['bourac|bourák', 'máy đục phá'],
 ['svářeč|svařovac|svářec|svařec', 'máy hàn'], ['elektrod', 'que hàn'],
 ['kompresor', 'máy nén khí'], ['pneumatick', 'khí nén'], ['hustilk', 'bơm hơi'],
 ['pájk|pájec', 'mỏ hàn thiếc'], ['kalafun', 'nhựa thông'],
 ['vysavač', 'máy hút bụi'], ['čerpadl', 'máy bơm'], ['míchadl|míchačk', 'máy trộn'],
 ['sekačk', 'máy cắt cỏ'], ['krovinořez', 'máy phát cỏ'], ['štěpkovač|drtič', 'máy băm cành'],
 ['hořák', 'đèn khò'], ['generátor|elektrocentrál', 'máy phát điện'],
 ['motor', 'động cơ'], ['ložisk', 'vòng bi'], ['převodovk', 'hộp số'],
 // ===== đo đạc =====
 ['vodováh', 'thước thủy'], ['libel', 'bọt thủy'], ['bedn[íi]c', 'cốp pha'], ['úhelník', 'êke'], ['úhloměr', 'thước đo góc'],
 ['pravítk', 'thước thẳng'], ['metr', 'thước'], ['pásmo|pásem', 'thước dây'],
 ['svinovac', 'cuộn'], ['skládac', 'gấp'], ['posuvn', 'trượt'],
 ['mikrometr', 'panme'], ['měřidl|měřítk|měřic', 'dụng cụ đo'], ['měřen', 'đo'],
 ['dálkoměr', 'máy đo khoảng cách'], ['laser', 'laser'], ['olovnic', 'quả dọi'],
 ['brnkačk', 'dây bật mực'], ['značkovač|popisovač', 'bút đánh dấu'], ['rýsovac', 'vạch dấu'],
 ['zkoušečk|tester', 'bút thử điện'], ['multimetr', 'đồng hồ vạn năng'],
 ['vlhkoměr', 'máy đo ẩm'], ['teploměr', 'nhiệt kế'], ['detektor', 'máy dò'],
 ['váh(a|y|u)', 'cân'], ['lať|latě', 'thước nhôm cán'],
 // ===== thợ nề / xây dựng =====
 ['hladítk', 'bàn xoa'], ['stěrk', 'bay trét'], ['špachtl', 'bay nhỏ'],
 ['škrabák|škrabk', 'dụng cụ cạo'], ['struhadl', 'bàn nạo'],
 ['lžíc', 'bay xây'], ['naběrač|nabírač', 'gáo múc'], ['vědr|kbelík|kýbl|kbelic', 'xô'],
 ['maltovník', 'chậu trộn vữa'], ['zednick', 'thợ nề'], ['omítk', 'vữa trát'],
 ['křížk', 'ke chữ thập'], ['klínk', 'nêm'], ['řezačk', 'máy cắt gạch'],
 ['žebřík', 'thang'], ['štafl|schůdk', 'thang ghế'], ['lešen', 'giàn giáo'],
 ['podpěr|rozpěr|stojk', 'cây chống'], ['koz(a|y)', 'giá đỡ'],
 ['dlažb|dlaždic', 'gạch lát'], ['obklad', 'gạch ốp'], ['sádrokarton', 'thạch cao'],
 ['beton', 'bê tông'], ['cement', 'xi măng'], ['malt', 'vữa'], ['sádr', 'thạch cao'],
 ['nivelačn', 'cân bằng'], ['stavebn', 'xây dựng'],
 // ===== hóa chất xây dựng, sơn =====
 ['silikon', 'silicon'], ['tmel', 'keo trám'], ['akryl', 'acrylic'],
 ['lepidl|lepidel', 'keo dán'], ['pěn(a|y|u|ě)', 'bọt nở'], ['penetrac', 'sơn lót'],
 ['hydroizolac|izolac', 'chống thấm'], ['asfalt', 'nhựa đường'],
 ['barv', 'sơn'], ['lak', 'vecni'], ['email', 'sơn men'], ['lazur', 'sơn phủ gỗ'],
 ['ředidl|rozpouštědl', 'dung môi pha'], ['aceton', 'axeton'], ['terpentýn', 'dầu thông'],
 ['štětec|štětc|štětk', 'chổi sơn'], ['váleček|válečk', 'con lăn sơn'],
 ['malířsk|natěračsk', 'sơn quét'], ['vanička', 'khay sơn'], ['molitan', 'mút xốp'],
 ['sprej|spray', 'bình xịt'], ['kartuš', 'ống keo'], ['maskovac', 'che chắn'],
 // ===== kim khí, liên kết =====
 ['šroub', 'bu lông'], ['vrut', 'vít gỗ'], ['samořez', 'vít tự khoan'],
 ['matic', 'đai ốc'], ['podložk', 'long đen'], ['hmoždink', 'tắc kê'],
 ['kotv', 'bu lông neo'], ['závit', 'ren'], ['závlačk', 'chốt chẻ'],
 ['řetěz', 'xích'], ['lan(o|a|ka|ko)', 'dây cáp'], ['popruh|pás(ek|ku)', 'dây đai'],
 ['drát', 'dây thép'], ['provaz|motouz|šňůr', 'dây thừng'], ['kladk', 'ròng rọc'],
 ['napínák|napínac', 'tăng đơ'], ['karabin', 'móc khóa'],
 ['hák|háček', 'móc'], ['skob', 'đinh móc'], ['úchytk|úchyt', 'tay nắm'],
 ['konzol', 'giá đỡ'], ['pant', 'bản lề'], ['závěs', 'bản lề treo'],
 ['zámek|zámk', 'khóa'], ['vložk', 'ruột khóa'], ['petlic|zástrč|závor', 'then cài'],
 ['klik(a|y|ou)', 'tay nắm cửa'], ['kován', 'phụ kiện cửa'], ['trezor', 'két sắt'],
 ['schránk', 'hòm thư'], ['visac', 'treo'],
 ['plech', 'tấm tôn'], ['profil', 'thanh định hình'], ['mřížk', 'lưới'],
 ['pletiv', 'lưới rào'], ['palisád|plůtek', 'hàng rào'],
 ['páska|pásky|páskou', 'băng dính'], ['lepic|lepíc', 'dính'], ['izolačn', 'cách điện'],
 ['bužírk|smršťovac', 'ống co nhiệt'], ['stahovac', 'siết'],
 // ===== điện =====
 ['žárovk', 'bóng đèn'], ['zářivk', 'đèn huỳnh quang'], ['svítiln|baterk|celovk', 'đèn pin'],
 ['lamp|lampičk', 'đèn'], ['reflektor', 'đèn pha'], ['svítidl|osvětlen|světl', 'đèn chiếu sáng'],
 ['objímk', 'đui đèn'], ['zásuvk', 'ổ cắm'], ['vypínač', 'công tắc'],
 ['prodlužovac', 'nối dài'], ['kabel|kabelov', 'dây điện'], ['buben', 'cuộn tang'],
 ['svork|svorkovnic', 'cầu đấu'], ['dutink', 'đầu cốt'], ['krabic', 'hộp'],
 ['baterie|baterií|baterek', 'pin'], ['akumulátor|aku', 'ắc quy'], ['nabíječk', 'sạc'],
 ['powerbank', 'sạc dự phòng'], ['sluchátk', 'tai nghe'], ['ventilátor', 'quạt'],
 ['topidl', 'máy sưởi'], ['ohřívač', 'máy làm nóng'], ['časovač', 'hẹn giờ'],
 ['zvonek|zvonk', 'chuông cửa'], ['alarm', 'báo động'], ['čidl|senzor', 'cảm biến'],
 // ===== bảo hộ lao động =====
 ['rukavic', 'găng tay'], ['obuv|bot(a|y)', 'giày'], ['polobotk', 'giày thấp cổ'],
 ['kotníkov', 'cổ cao'], ['sandál', 'dép quai hậu'], ['holínk|gumák', 'ủng'],
 ['dřevák|filcák', 'guốc bảo hộ'], ['nazouvák|pantofl', 'dép'], ['žabk', 'dép xỏ ngón'],
 ['kalhot', 'quần'], ['kraťas|šortk', 'quần short'], ['zahradník', 'quần yếm'],
 ['montérk', 'đồ bảo hộ'], ['blůz', 'áo bảo hộ'], ['tričk|trik(o|a)', 'áo phông'],
 ['košil|polokošil', 'áo sơ mi'], ['mikin', 'áo nỉ'], ['bund', 'áo khoác'],
 ['vest(a|y|u)', 'áo gi lê'], ['kabát', 'áo măng tô'], ['kombinéz|overal', 'áo liền quần'],
 ['zástěr', 'tạp dề'], ['rondon', 'áo đầu bếp'], ['ponožk', 'tất'],
 ['čepic|kukl', 'mũ'], ['přilb|helm', 'mũ bảo hộ'], ['zornik|zorník', 'kính che mặt'],
 ['brýl', 'kính'], ['respirátor|polomask', 'khẩu trang'], ['chránič', 'đồ bảo vệ'],
 ['postroj', 'dây an toàn toàn thân'], ['nákolen', 'đệm đầu gối'],
 ['reflexn|výstražn', 'phản quang'], ['bezpečnostn', 'an toàn'], ['ochrann', 'bảo vệ'],
 ['pracovn', 'lao động'], ['samolepk', 'nhãn dán'], ['tabulk', 'biển báo'],
 // ===== làm vườn =====
 ['květník|květináč', 'chậu hoa'], ['truhlík', 'chậu dài'], ['žardink|žardin', 'chậu ban công'],
 ['podmisk', 'đĩa lót chậu'], ['sadbovač', 'khay ươm'],
 ['rýč', 'xẻng'], ['lopat', 'xẻng xúc'], ['vidl(e|í)', 'chĩa'],
 ['hrábě|hrabičk|hrabl', 'cào'], ['motyk|okopávač|kypřič|kultivátor', 'cuốc xới'],
 ['sekyr|sekera|sekerk', 'rìu'], ['kalač|štípac', 'bổ củi'], ['krumpáč', 'cuốc chim'],
 ['kos(a|y|ou)|kosišt', 'lưỡi hái'], ['srp', 'liềm'], ['mačet', 'dao rựa'],
 ['plotostrih|plotostřih', 'kéo tỉa hàng rào'], ['prořezávač|zastřihovač', 'kéo tỉa'],
 ['násad', 'cán'], ['topůrk|držadl|rukojeť|rukojet', 'tay cầm'],
 ['kolečk', 'xe rùa'], ['vozík|rudl', 'xe đẩy'], ['klekátk', 'ghế quỳ'],
 ['hnojiv', 'phân bón'], ['substrát|zemin|rašelin', 'giá thể'], ['kompost', 'phân ủ'],
 ['mulč|kůr(a|y)', 'vỏ cây phủ'], ['osiv|semen', 'hạt giống'], ['sadb', 'cây giống'],
 ['postřik', 'thuốc phun'], ['herbicid', 'thuốc diệt cỏ'], ['insekticid', 'thuốc diệt côn trùng'],
 ['fungicid', 'thuốc diệt nấm'], ['repelent|odpuzovač', 'thuốc xua đuổi'],
 ['past(i|í)?|lapač|mucholapk', 'bẫy'], ['stimulátor', 'chất kích thích'],
 ['netkan', 'vải không dệt'], ['stínovk|stínic', 'lưới che nắng'], ['textili', 'vải'],
 ['plachta|plachet|plachtou', 'bạt'], ['fóli', 'màng phủ'], ['skleník|fóliovník|pařeništ', 'nhà kính'],
 ['tyč', 'cọc'], ['opěr|opor', 'giá đỡ cây'], ['obrub', 'viền bồn'],
 // ===== tưới tiêu =====
 ['hadic', 'ống mềm'], ['rychlospojk', 'khớp nối nhanh'], ['spojk', 'khớp nối'],
 ['postřikovač', 'bình phun'], ['rozprašovač', 'bình xịt'], ['zavlažovač|zavlažovac', 'tưới cây'],
 ['konev|konv(e|i)|konvičk', 'bình tưới'], ['tryska', 'béc phun'], ['navijak|naviják', 'cuộn ống'],
 ['sud|barel|kanystr', 'thùng chứa'], ['nádob|nádrž', 'bình chứa'], ['popelnic', 'thùng rác lớn'],
 ['trychtýř|trycht', 'phễu'],
 // ===== cấp thoát nước =====
 ['ventil', 'van'], ['kohout', 'vòi'], ['sifon', 'xi phông'], ['perlátor', 'đầu lọc vòi'],
 ['sprch', 'vòi sen'], ['koleno', 'cút nối'], ['nipl|vsuvk|mufn|přechodk', 'đầu nối ren'],
 ['redukc', 'đầu thu'], ['šroubení', 'đầu nối ren'], ['trubk|roura', 'ống'],
 ['těsněn', 'gioăng'], ['kroužek|kroužk', 'vòng đệm'], ['manžet', 'măng sông'],
 ['příruba|přírubov', 'mặt bích'], ['radiátor', 'lò sưởi'], ['kouřovod|kouřov', 'ống khói'],
 ['komínov', 'ống khói'], ['okap|žlab', 'máng xối'], ['teflon', 'băng tan'],
 // ===== ô tô =====
 ['stěrač', 'gạt mưa'], ['ostřikovač', 'nước rửa kính'], ['nemrznouc', 'chống đông'],
 ['chladic', 'làm mát'], ['brzdov', 'phanh'], ['olej', 'dầu nhớt'], ['mazivo|maziv|maza', 'mỡ bôi trơn'],
 ['vazelín', 'vaseline'], ['antifreeze', 'nước làm mát'], ['autošampon', 'nước rửa xe'],
 ['osvěžovač', 'sáp thơm'], ['leštěnk', 'xi đánh bóng'], ['zvedák|zvedac', 'kích nâng'],
 ['autopotah', 'bọc ghế'], ['autokoberc', 'thảm sàn xe'], ['tachograf', 'đồng hồ hành trình'],
 ['pneu|pneumatik', 'lốp'], ['autobateri', 'ắc quy xe'],
 // ===== gia dụng, lau dọn =====
 ['smeták|smetáček', 'chổi quét'], ['koště|kostě', 'chổi'], ['mop', 'cây lau nhà'],
 ['lopatk', 'xẻng hót rác'], ['utěrk|utierk', 'khăn lau'], ['hadr', 'giẻ lau'],
 ['houbičk', 'mút rửa chén'], ['houb(a|y|ou)', 'bọt biển'], ['drátěnk', 'miếng cọ kim loại'],
 ['stírk|stěrač', 'gạt nước'], ['ždímac', 'vắt'], ['lavor', 'chậu'],
 ['koš|košík', 'giỏ'], ['pytel|pytl|sáček|sáčk', 'túi'], ['odpadkov', 'đựng rác'],
 ['box|krabic|dóz', 'hộp'], ['úložn', 'lưu trữ'], ['přepravk|bedn', 'két đựng'],
 ['regál|polic|poličk', 'kệ'], ['věšák', 'móc treo'], ['sušák', 'giàn phơi'],
 ['kolíček|kolíčk', 'kẹp phơi'], ['žehlic', 'là ủi'], ['rohož|rohožk', 'thảm chùi chân'],
 ['koberec|koberc|předložk', 'thảm'], ['ubrus|prostíran', 'khăn trải bàn'],
 ['polštář|podsedák', 'đệm ngồi'], ['dek(a|y)|přikrývk', 'chăn'], ['záclon|závěs y', 'rèm'],
 // ===== nhà bếp =====
 ['hrnec|hrnc', 'nồi'], ['pánev|pánv', 'chảo'], ['kastrol|rendlík|pekáč', 'nồi nướng'],
 ['poklic', 'vung nồi'], ['miska|misk|mís(a|y)', 'bát'], ['talíř', 'đĩa'],
 ['hrnek|hrnk|šálek', 'cốc'], ['sklenic|skleněn', 'thủy tinh'], ['láhev|lahv', 'chai'],
 ['džbán|karaf', 'bình rót'], ['podnos|tácek|tác', 'khay'], ['cukřenk|kořenk', 'lọ gia vị'],
 ['příbor|příborn', 'bộ dao dĩa'], ['lžíc(e|i)|lžičk', 'thìa'], ['vidličk', 'dĩa'],
 ['cedník', 'rổ lọc'], ['odměrk', 'cốc đong'], ['naběračk', 'muôi'],
 ['obraceč', 'xẻng lật'], ['struhadl', 'bàn nạo'], ['škrabk', 'dao bào'],
 ['otvírák|vývrtk', 'đồ khui'], ['mlýnek', 'cối xay'], ['šlehač|metličk', 'phới đánh trứng'],
 ['prkénk|prkýnk', 'thớt'], ['form(a|y|ě|u)', 'khuôn'], ['formičk', 'khuôn nhỏ'],
 ['vykraj', 'khuôn cắt bánh'], ['vařečk', 'đũa cả'], ['odkapávač', 'giá úp'],
 ['alobal|mikroten|potravinov', 'màng bọc thực phẩm'], ['zátk', 'nút chai'],
 ['termosk|termohrnek', 'bình giữ nhiệt'],
 // ===== nến, trang trí =====
 ['svíčk|svíce|svíc', 'nến'], ['svícen', 'chân nến'], ['knot', 'bấc nến'],
 ['kahanec|hřbitovn', 'nến mộ'], ['vonn|vůn(e|í)', 'thơm'],
 ['dekorac|dekoračn|ozdob', 'trang trí'], ['váza|váz', 'lọ hoa'],
 ['věnec|věneč', 'vòng hoa'], ['sušin', 'hoa khô'], ['stromek|stromeč', 'cây thông'],
 ['balónek|balónk|balonek', 'bóng bay'], ['konfet|prskavk', 'pháo giấy'],
 ['stuh(a|y|ou)|mašl', 'ruy băng'], ['celofán', 'giấy bóng kính'],
 ['vánočn|adventn', 'Giáng sinh'], ['velikonočn', 'Phục sinh'],
 ['girland|lampión', 'đèn lồng dây'], ['polystyren', 'xốp'],
 // ===== văn phòng phẩm =====
 ['propisk', 'bút bi'], ['pero|per(a|u)', 'bút'], ['tužk', 'bút chì'],
 ['fix(a|y|ou)?|fixy', 'bút lông'], ['zvýrazňovač', 'bút dạ quang'], ['pastelk', 'bút màu'],
 ['sešit', 'vở'], ['blok', 'sổ tay'], ['diář|kalendář', 'sổ lịch'],
 ['papír', 'giấy'], ['čtvrtk', 'giấy vẽ'], ['karton', 'bìa cứng'],
 ['obálk', 'phong bì'], ['pořadač|zakladač|rychlovazač', 'bìa còng'],
 ['desk(a|y|ou)', 'bìa hồ sơ'], ['obal', 'vỏ bọc'], ['spisov', 'hồ sơ'],
 ['sešívačk', 'dập ghim'], ['spon(a|y|ka|ky)', 'kẹp giấy'], ['děrovačk', 'đục lỗ'],
 ['ořezávátk|ořezáv', 'gọt bút chì'], ['gum(a|y)', 'tẩy'], ['korektor|zmizík', 'bút xóa'],
 ['kalkulačk', 'máy tính'], ['razítk', 'con dấu'], ['křid|křít', 'phấn'],
 ['modelín|plastelín', 'đất nặn'], ['temper', 'màu bột'], ['moosgummi|filc', 'mút xốp'],
 ['blahopřán', 'thiệp chúc mừng'],
 // ===== hóa mỹ phẩm =====
 ['šampon', 'dầu gội'], ['kondicionér', 'dầu xả'], ['tužidl', 'gôm tạo kiểu'],
 ['mýdl', 'xà phòng'], ['deodorant|antiperspirant', 'lăn khử mùi'],
 ['holic|holen', 'cạo râu'], ['žilet', 'lưỡi dao cạo'], ['zubn', 'răng miệng'],
 ['krém|krem', 'kem'], ['gel', 'gel'], ['kapesník|kapesníč', 'khăn giấy'],
 ['ubrousek|ubrousk|ubrousky', 'khăn ướt'], ['vat(a|y)', 'bông'],
 ['prac(í|ího)|prášek na praní', 'bột giặt'], ['aviváž', 'nước xả vải'],
 ['čistič|čistic|čistíc', 'chất tẩy rửa'], ['odmašťov', 'tẩy dầu mỡ'],
 ['toaletn', 'vệ sinh'], ['vložk', 'băng vệ sinh'],
 // ===== mùa, giải trí =====
 ['gril', 'bếp nướng'], ['brikety|uhlí', 'than'], ['podpalovač|zapalovač', 'mồi lửa'],
 ['vařič', 'bếp'], ['kartuš', 'bình gas mini'], ['stan', 'lều'],
 ['spacák|spac', 'túi ngủ'], ['lehátk', 'ghế nằm'], ['slunečník', 'ô che nắng'],
 ['bazén|bazénov', 'bể bơi'], ['nafukovac', 'bơm hơi'], ['chlor', 'clo'],
 ['sáňk|boby', 'xe trượt tuyết'], ['sněhov|sníh|sněh', 'tuyết'], ['posypov|sůl', 'muối rắc'],
 ['hračk', 'đồ chơi'], ['míč', 'bóng'], ['bublifuk', 'thổi bong bóng'],
 ['krmiv|krmítk|krmn', 'thức ăn vật nuôi'], ['obojek|vodítk', 'vòng cổ dây dắt'],
 // ===== vật liệu =====
 ['plastov|plast', 'nhựa'], ['pryž|pryžov|gumov', 'cao su'], ['siliko', 'silicon'],
 ['nerez|nerezov', 'inox'], ['ocel|ocelov', 'thép'], ['železn|litin', 'gang'],
 ['hliník|hliníkov', 'nhôm'], ['mosaz|mosazn', 'đồng thau'], ['měď|měděn', 'đồng đỏ'],
 ['zinkov|pozinkov', 'mạ kẽm'], ['chrom|chromov', 'mạ crôm'], ['niklov', 'mạ niken'],
 ['dřevěn|dřev(o|a)', 'gỗ'], ['bambusov|bambus', 'tre'], ['proutí|ratan|rattan', 'mây'],
 ['keramick|keramic', 'gốm sứ'], ['sklo|skleněn', 'thủy tinh'], ['porcelán', 'sứ'],
 ['bavln', 'cotton'], ['polyester', 'polyester'], ['nylon|nylonov', 'nylon'],
 ['kožen|kůž', 'da'], ['textiln', 'vải'], ['fíbr|fibr', 'sợi fibre'],
 ['papírov', 'giấy'], ['kovov|kov(u|em)?', 'kim loại'], ['diamantov', 'kim cương'],
 ['magnetick|magnet', 'nam châm'], ['přírodn', 'tự nhiên'],
 // ===== màu sắc =====
 ['bíl|bílo', 'trắng'], ['čern|černo|čer\\b', 'đen'], ['šed|šedo', 'xám'],
 ['červen|červeno', 'đỏ'], ['modr|modro', 'xanh dương'], ['zelen|zeleno', 'xanh lá'],
 ['žlut|žluto', 'vàng'], ['oranžov|oranžovo', 'cam'], ['hněd|hnědo', 'nâu'],
 ['fialov', 'tím'], ['růžov', 'hồng'], ['zlat', 'vàng kim'], ['stříbrn', 'bạc'],
 ['barevn|barv', 'màu'], ['průhledn|transparentn', 'trong suốt'],
 ['lesk(lý|lá|lé)|lesklý', 'bóng'], ['matn|mat\\b', 'nhám mờ'], ['metalick', 'ánh kim'],
 ['tmav|tmavě', 'đậm'], ['svět(lý|lá|lé)|světle', 'nhạt'],
 // ===== tính từ, thuộc tính chung =====
 ['univerzáln', 'đa năng'], ['ruční|ručn', 'cầm tay'], ['elektrick', 'chạy điện'],
 ['akumulátorov', 'dùng pin'], ['profesionáln|profi', 'chuyên nghiệp'],
 ['náhradn', 'thay thế'], ['nastaviteln|stavitel', 'điều chỉnh được'],
 ['skládac', 'gấp gọn'], ['teleskopick|výsuvn', 'rút gọn'], ['prodloužen|prodloužn', 'dài thêm'],
 ['samolepic|samolepíc', 'tự dính'], ['samozavlažovac', 'tự tưới'],
 ['oboustrann', 'hai mặt'], ['jednoráz', 'dùng một lần'],
 ['voděodoln|vodotěsn|nepromokav', 'chống nước'], ['zateplen|zimn', 'giữ ấm'],
 ['letn', 'mùa hè'], ['vnitřn', 'trong nhà'], ['vnějš|venkovn', 'ngoài trời'],
 ['závěsn', 'treo'], ['stolní|stoln', 'để bàn'], ['stojan|stojac', 'chân đế'],
 ['přenosn|mobiln', 'di động'], ['sklápěc|otočn', 'xoay'],
 ['ploch(ý|á|é)', 'dẹt'], ['kulat|kruhov', 'tròn'], ['hranat|čtvercov', 'vuông'],
 ['oblý|oválný|oválná', 'bầu dục'], ['špičat', 'nhọn'], ['zahnut', 'cong'],
 ['dlouh', 'dài'], ['krátk', 'ngắn'], ['širok', 'rộng'], ['úzk', 'hẹp'],
 ['velikost|vel\\.?', 'cỡ'],
 ['velk(ý|á|é|ých|ém|ým)', 'lớn'], ['mal(ý|á|é|ých)', 'nhỏ'], ['středn', 'trung bình'],
 ['siln|pevn', 'chắc khỏe'], ['lehk|lehčen', 'nhẹ'], ['těžk', 'nặng'],
 ['tenk', 'mỏng'], ['tlust', 'dày'], ['jemn', 'mịn'], ['hrub', 'thô'],
 ['nov(ý|á|é)', 'mới'], ['star(ý|á|é)', 'cũ'], ['dětsk', 'trẻ em'],
 ['pánsk', 'nam'], ['dámsk', 'nữ'], ['unisex', 'unisex'],
 ['dvojit|dvoj', 'đôi'], ['trojit|troj', 'ba'], ['sam(a|o)stat', 'riêng lẻ'],
 // ===== danh từ chung =====
 ['sad(a|y|u|ě)|soupravu|souprav', 'bộ'], ['balení|balen|bal\\b', 'gói'],
 ['kus|kusů|ks', 'cái'], ['pár|páru', 'đôi'], ['role|rol', 'cuộn'],
 ['díl|dílů|díln', 'chi tiết'], ['náplň|náplň', 'ruột thay'],
 ['držák|držadl', 'giá đỡ'], ['kryt|víko|víčk', 'nắp'], ['podstavec', 'đế'],
 ['průměr', 'đường kính'], ['délk', 'chiều dài'], ['šířk', 'chiều rộng'],
 ['výšk', 'chiều cao'], ['tloušťk', 'độ dày'], ['nosnost', 'tải trọng'],
 ['hmotnost|váh', 'trọng lượng'], ['objem', 'dung tích'], ['obsah', 'thể tích'],
 ['velikost|vel\\b', 'cỡ'], ['typ', 'loại'], ['provedení', 'kiểu'],
 ['zub|zubů', 'răng'], ['otvor|otvorů', 'lỗ'], ['čísl', 'số'],
 ['směs|smes', 'hỗn hợp'], ['mix', 'hỗn hợp'], ['sortiment', 'chủng loại'],
 // ===== bổ sung đợt 2 =====
 ['doplněk|doplňk|příslušenstv', 'phụ kiện'], ['korunk', 'mũi khoét'],
 ['pistol', 'súng'], ['blistr', 'vỉ treo'], ['kniha|knih', 'sổ'],
 ['dveř(e|í)|dveřn', 'cửa'], ['okenn|okno|okna', 'cửa sổ'], ['tašk', 'túi xách'],
 ['strun', 'dây cước'], ['pouzdr', 'bao đựng'], ['ručk', 'tay nắm'],
 ['lišt', 'nẹp'], ['kol(o|a|ečk)', 'bánh xe'], ['kruh', 'vòng tròn'],
 ['vidlic', 'phích cắm'], ['růžic', 'hoa sen'], ['čtverec|čtvercov', 'vuông'],
 ['halen', 'áo nữ'], ['tkanin', 'vải dệt'], ['kámen|kamen', 'đá'],
 ['latex|latexov', 'cao su latex'], ['hrot', 'đầu nhọn'], ['kapalin', 'dung dịch'],
 ['oblek', 'bộ đồ'], ['rostlin', 'cây trồng'], ['hmot', 'vật liệu'],
 ['svazek|svazk', 'bó'], ['patk', 'đế chân'], ['sloupek|sloupk', 'cột'],
 ['cibul', 'củ giống'], ['potisk', 'in hình'], ['dlaň|dlaňov', 'lòng bàn tay'],
 ['hran', 'cạnh'], ['potah', 'bọc'], ['rozteč', 'khoảng cách tâm'],
 ['zahradn', 'làm vườn'], ['nářad', 'dụng cụ'], ['montážn', 'lắp ráp'],
 ['zakrývac', 'che phủ'], ['upínac', 'kẹp giữ'], ['rotačn', 'xoay tròn'],
 ['odlamovac', 'bẻ đốt'], ['lamelov', 'nhám xếp'], ['spirál|spirálov', 'xoắn'],
 ['křížov|křížk', 'chữ thập'], ['vlnit', 'gợn sóng'], ['kónick', 'côn'],
 ['impregnovan', 'tẩm chống thấm'], ['neutráln', 'trung tính'],
 ['funkčn|multifunkčn', 'đa chức năng'], ['pomocn', 'hỗ trợ'],
 ['zámečnick', 'cơ khí'], ['truhlářsk|tesařsk', 'mộc'], ['instalatérsk', 'nước'],
 ['elektrikářsk', 'điện'], ['malířsk', 'sơn'], ['sklenářsk', 'kính'],
 ['máčen', 'nhúng phủ'], ['vybrušovan', 'mài bóng'], ['vidiov', 'hợp kim cứng'],
 ['travn', 'cỏ'], ['sluneční|slunečn', 'nắng'], ['dárkov', 'quà tặng'],
 ['tlakov', 'áp lực'], ['fleecov', 'nỉ lông cừu'], ['přípravek|přípravk', 'chế phẩm'],
 ['vysok', 'cao'], ['nízk', 'thấp'], ['hvězd', 'sao'], ['ochran', 'bảo vệ'],
 ['odpad', 'thoát rác'], ['vzduch', 'không khí'], ['povrch', 'bề mặt'],
 ['segment', 'đoạn'], ['panel', 'tấm'], ['rozet', 'đế tròn'],
 ['aranžován|aranž', 'cắm hoa'], ['dekorů|dekor', 'họa tiết'], ['gramáž', 'định lượng'],
 ['cukroví', 'bánh quy'], ['rychlen', 'trồng sớm'], ['zeleninov', 'rau'],
 ['ředkvičk', 'củ cải'], ['rajče|rajčat', 'cà chua'], ['okurk', 'dưa chuột'],
 ['paprik', 'ớt chuông'], ['mrkev|mrkv', 'cà rốt'], ['tykev|tykv', 'bí ngô'],
 ['fazol', 'đậu'], ['hrách|hrachov', 'đậu Hà Lan'], ['salát', 'xà lách'],
 ['orchidej', 'lan'], ['jasan|dub|buk|smrk', 'gỗ tự nhiên'],
 ['filtr', 'lọc'], ['hlav(a|y|ou)', 'đầu'], ['list(y|ů|u)', 'lưỡi'],
 ['textil', 'vải'], ['elastan', 'thun co giãn'], ['khaki', 'kaki'],
 ['polyuretan', 'PU'], ['barev|barvách', 'màu'], ['skl(e|a|em)', 'thủy tinh'],
 // ===== bổ sung đợt 3 =====
 ['nitril', 'nitrile'], ['koul', 'quả cầu'], ['gum(a|y|ou|ov)', 'cao su'],
 ['pružin', 'lò xo'], ['odstraňovač', 'chất tẩy'], ['lesk', 'độ bóng'],
 ['spodk|prádl', 'đồ lót'], ['madl', 'tay vịn'], ['ok(o|a)|očk', 'khuyên'],
 ['okn(o|a|em)|oken', 'cửa sổ'], ['ruk(a|ou)|ruce|ručn', 'tay'], ['klip|klipem', 'kẹp'],
 ['kobalt', 'coban'], ['slitin', 'hợp kim'], ['pořez|řez', 'cắt'],
 ['kuličk', 'bi tròn'], ['diamant', 'kim cương'], ['keramik', 'gốm'],
 ['trub(ka|ky|ek|ce)', 'ống'], ['prostředek|prostředk', 'chất'], ['břit', 'lưỡi cắt'],
 ['pol(e|í)', 'ruộng'], ['koncovk', 'đầu bịt'], ['dno|dna', 'đáy'],
 ['vratn|vratov', 'hồi vị'], ['motyčk', 'cuốc nhỏ'], ['polyetylen|polyethylen', 'PE'],
 ['spis', 'hồ sơ'], ['vratidl', 'tay quay taro'], ['palič', 'búa cao su'],
 ['kedluben', 'su hào'], ['stojin', 'thân đứng'], ['rameno|ramínk', 'cần'],
 ['větv', 'cành'], ['imitac', 'giả'], ['tablet', 'viên nén'],
 ['cukr', 'đường'], ['arch', 'tờ'], ['trn', 'trục gá'],
 ['krabičk', 'hộp nhỏ'], ['roh|rohov', 'góc'], ['litr|litrů', 'lít'],
 ['jablk', 'táo'], ['aditiv', 'phụ gia'], ['ovoc', 'trái cây'],
 ['disk', 'đĩa'], ['spoj', 'mối nối'], ['volně', 'rời'],
 ['tub(a|y|ě)', 'tuýp'], ['podlah', 'sàn'], ['sejf', 'két'],
 ['chilli', 'ớt'], ['petržel', 'ngò tây'], ['buben|bubnu', 'tang trống'],
 ['kužel', 'côn'], ['průhled', 'trong suốt'], ['dvoumetr', 'thước gấp 2m'],
 ['antracit', 'xám than'], ['samolep', 'tự dính'], ['zip|zipem', 'khóa kéo'],
 ['sluch', 'thính giác'], ['auto|auta', 'ô tô'], ['vod(a|u|y|ě)', 'nước'],
 ['komplet', 'trọn bộ'], ['tělo|těl', 'thân'], ['sad', 'bộ'],
];

// giới từ / liên từ hay gặp — khớp đúng chữ, không đuôi
var WORDS = [
 ['na', 'cho'], ['pro', 'cho'], ['do', 'cho'], ['k|ke', 'cho'],
 ['bez', 'không'], ['pod', 'dưới'], ['nad', 'trên'], ['v|ve', 'trong'],
 ['s|se', 'có'], ['z|ze', 'bằng'], ['proti', 'chống'], ['a', 'và'],
 ['nebo', 'hoặc'], ['pr\.?', 'đk'], ['tl\.?', 'dày'], ['zn\.?', 'mạ kẽm'],
];

function esc(s) { return s; }
var RULES = [];
PHRASES.forEach(function (p) {
  RULES.push([new RegExp('(?<!\\p{L})(?:' + p[0] + ')(?!\\p{L})', 'giu'), p[1]]);
});
// WORDS (giới từ) chạy TRƯỚC STEMS: nếu chạy sau, chúng sẽ ăn vào chính kết quả tiếng Việt
// vừa sinh ra — vd. 'úhelník' -> 'êke' rồi 'ke' -> 'cho' thành 'ê cho'.
WORDS.forEach(function (p) {
  RULES.push([new RegExp(word(p[0]), 'giu'), p[1]]);
});
STEMS.forEach(function (p) {
  RULES.push([new RegExp(stem(p[0]), 'giu'), p[1]]);
});
// số lượng + đơn vị
RULES.push([/(\d+)\s*ks(?!\p{L})/giu, '$1 cái']);
RULES.push([/(\d+)\s*(ks\/bal|ks v bal\.?)(?!\p{L})/giu, '$1 cái/gói']);

window.viTranslate = function (name) {
  var s = String(name || '');
  for (var i = 0; i < RULES.length; i++) s = s.replace(RULES[i][0], RULES[i][1]);
  return s.replace(/\s{2,}/g, ' ').trim();
};

// diacritic-insensitive search key (CZ + VI)
window.searchNorm = function (s) {
  return String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[đĐ]/g, 'd').toLowerCase();
};
})();
